baseURL = "http://blog.yentheoerlemans.com/"
languageCode = "en-us"
title = "My Personal Holocron"
theme = "hugo-notepadium"
staticDir = ["static"]

disqusShortname = "blog-yentheoerlemans"

[params.comments]
enable = true